### ISSUE TITLE
"Getting started - test your setup" section looks to be using wrong backend field

### ISSUE THREAD

**Issue by mriedem** [ibm-cloud-docs/quantum-computing#2]
Going through https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-quickstart I got to this sample code snippet:

```python
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService()
program_inputs = {'iterations': 1}
options = {"backend_name": ""}
job = service.run(program_id="hello-world",
                  options=options,
                  inputs=program_inputs
                 )
print(f"job id: {job.job_id}")
result = job.result()
print(result)
```

The `options = {"backend_name": ""}` doesn't seem to align with https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.QiskitRuntimeService.run.html#qiskit_ibm_runtime.QiskitRuntimeService.run where it shows `options` to map to this:

https://qiskit.org/documentation/partners/qiskit_ibm_runtime/stubs/qiskit_ibm_runtime.RuntimeOptions.html#qiskit_ibm_runtime.RuntimeOptions

Which says there is a `backend` parameter, not `backend_name` as in the code sample above:

![image](https://user-images.githubusercontent.com/3237936/201180759-b860413d-2556-4e10-aa6a-04b29c9d1846.png)

**Comment by mriedem** [comment]
Also note that when I ran that code sample I got a deprecation warning:

>/tmp/ipykernel_60/24275224.py:11: DeprecationWarning: Note that the 'job_id' and 'backend' attributes of a runtime job have been deprecated as of qiskit-ibm-runtime 0.7 and will be removed no sooner than 3 months after the release date. Please use the job_id() and backend() methods instead.
  job = service.run(program_id="hello-world",

My guess is the fix is simply changing this:

```python
print(f"job id: {job.job_id}")
```

to this:

```python
print(f"job id: {job.job_id()}")
```

**Comment by beckykd** [comment]
That seems right - I'll double check with Kevin or Jessie to be sure.  Thanks!

**Comment by beckykd** [comment]
Kevin confirmed that you are correct on both suggestions.  I'm building now.

**Comment by beckykd** [comment]
Done @mriedem https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-quickstart#test-setup

**Comment by mriedem** [comment]
Looks good, thanks!
