### ISSUE TITLE
Broken link to "Qiskit Runtime plans"

### ISSUE THREAD

**Issue by mriedem** [ibm-cloud-docs/quantum-computing#3]
From this page:

https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-quickstart

![image](https://user-images.githubusercontent.com/3237936/201203972-333b3abf-8f21-4ca4-a31e-1a714392e113.png)

That goes here which says the page is missing:

https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-plans

![image](https://user-images.githubusercontent.com/3237936/201204050-45c04327-6cdc-48c6-85f9-09b45069d935.png)

**Comment by beckykd** [comment]
Good catch!  Fixed and building now.

**Comment by beckykd** [comment]
Done, @mriedem : https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-quickstart#create-configure

**Comment by mriedem** [comment]
Looks good, thanks!
